---
#title: "Start"
lang: de  
author: "J. Franz Th. Meißner"
format:
  html:
    toc: true
    toc-location: right
    theme: cosmo   # cosmo bootswatch theme
bibliography: references.bib
bibliographystyle: apa
---

# SprachFit am Übergang Kita–Schule: Diagnostische Kompetenz, datengestützte Steuerung und Multi-Level-Governance in Heidelberg und dem Rhein-Neckar-Kreis

**(Arbeitstitel)**

Sprachförderung

Dissertationsprojekt beschäftigt sich mit der Umsetzung von Sprachförderung im Rahmen der Umsetzung des baden-württembergischen Bildungsprogramm "Sprachfit" in der kommunalen Bildungslandschaft, insbesondere im Kontext der kommunalen Verwaltung, des Bildungsmonitorings und der Schulverwaltung in Baden-Württemberg. Der Fokus liegt dabei auf den Schnittstellen zwischen staatlicher Schulverwaltung, kommunalen Schulträgern, Gesundheitsämter und den Kindertageseinrichtung sowie Schule.

## Forschungsfrage 
*Wie wird das Landesprogramm SprachFit (Säule 1) im Rahmen des datenbasierten kommunalen Bildungsmanagements in Heidelberg und im Rhein-Neckar-Kreis implementiert, und welche Rolle spielen dabei ESU-Daten als diagnostische Grundlage, die professionellen Kompetenzen pädagogischer Fachkräfte sowie Multi-Level-Governance-Strukturen für die evidenzbasierte Steuerung und nachhaltige Verankerung der Sprachförderung am Übergang Kita–Grundschule?*

### Literatur

::: {#refs}
:::

**eingereichtes Exposé**

[**Exposé**](/Expose_Dissertation.pdf) 

Einordnung der Literatur [finden sich hier](sprachfit_mindmap.html)

# über mich

[**curriculum vitae**](/CV_2025.pdf) 


[{{< fa envelope >}}](mailto:j.f.th.meissner@gmail.com) [{{< fa brands github >}}](https://github.com/jfthm/) [{{< fa brands linkedin >}}](https://www.linkedin.com/in/jfthm) [{{< fa brands mastodon >}}](https://mastodon.berlin/@jfthm/)